footer-links:
  github: nhold
  twitter: NathanHold
  
name: Nathan Hold
description: My portfolio
url: https://nhold.github.io

author:
    name: Nathan Hold
    email: nathanhold@hotmail.com
    uri: https://nhold.github.io